apiVersion: batch/v1
kind: Job
metadata:
  namespace: security
  name: kube-bench-node
spec:
  template:
    spec:
      hostPID: true
      containers:
      - name: kube-bench
        image: kube-bench:v0.7.6
        command: ["./python2.7", "kube-bench-controller.py"]
        args: ["-cluster", "cluster-name", "-nodepool", "test", "-project", "project-name", "-targets", "node,policies,controlplane"]
        #command: ["/bin/sh"]
        #args: ["-c", "while true; sleep 10; do echo 'tool'; done"]
        volumeMounts:
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
        - name: etc-systemd
          mountPath: /etc/systemd
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          # /usr/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version.
          # You can omit this mount if you specify --version as part of the command.
        - name: usr-bin
          mountPath: /usr/bin
        - name: kube-bench
          mountPath: "/etc/kube-bench"
      restartPolicy: Never
      volumes:
      - name: var-lib-etcd
        hostPath:
          path: "/var/lib/etcd"
      - name: var-lib-kubelet
        hostPath:
          path: "/var/lib/kubelet"
      - name: etc-systemd
        hostPath:
          path: "/etc/systemd"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: usr-bin
        hostPath:
          path: "/usr/bin"
      - name: kube-bench
        secret:
          secretName: securitycontainer
          defaultMode: 256
