FROM ubuntu
RUN apt-get update && apt-get -y upgrade &&  apt-get install -y build-essential
RUN apt-get install -y alien
RUN alien -i oracle-instantclient-basic*.rpm
RUN alien -i oracle-instantclient-sqlplus*.rpm
RUN alien -i oracle-instantclient-devel*.rpm
RUN apt-get install -y libaio1
RUN sensible-editor /etc/ld.so.conf.d/oracle.conf
RUN ldconfig
CMD ["bash"]
