apiVersion: apps/v1
kind: Deployment
metadata:
  name: pronnetheus
spec:
  selector:
      matchLabels:
        name: pronnetheus
  replicas: 1
  template:
    metadata:
      labels:
        run: pronnetheus
    spec:
      containers:
      - name: pronnetheus
        image: ilcapone/hack-tool:v02
        command: ["/bin/sh"]
        args: ["-c", "while true; sleep 10; do echo 'tool'; done"]
