apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app-test
spec:
  selector:
    matchLabels:
      app: webapp
      department: it
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
        department: it
    spec:
      containers:
      - name: flask-app
        image: registry/vulnapp:v0008
        command: ["python", "app.py"]
        args: ["-user", "vulnuser", "-pass", "agherqg"]
        env:
        - name: "PORT"
          value: "5000"
